import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utls/request";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ results }) {
  const [Data, setData] = useState([]);
  console.log("RES:::", results.results);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={results?.results} />
    </>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  console.log('genre::',genre);
  let Data = [];
  const request = await fetch(
    `http://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());
  // const request = await fetch(
  //   `http://api.themoviedb.org/3${requests[genre]?.url}`
  // )
  // .then((res) => res.json());
  // .then((data) => Data=data);
  // console.log(Data);
  // console.log("DATA:::::", request);
  return {
    props: {
      results: request,
      // results:Data
    },
  };
}
